name: "Find Jira Tickets"
description: "Find Jira tickets from git changes"
inputs:
  ticket_regex:
    description: "Regex to find Jira tickets"
    required: true
outputs:
  jira_tickets:
    description: "Jira tickets found in the git commit range"
runs:
  using: "composite"
  steps:
    - run: |
        git log --pretty=format:'%B' ${{ github.event.before }}..${{ github.event.after }} > commit_data.txt
        tickets=$(grep -oPi "${{ inputs.ticket_regex }}" commit_data.txt | sort -u | tr '\n' ' ')
        echo "Found Jira tickets: $tickets"
        echo "jira_tickets=$tickets" >> $GITHUB_ENV
      shell: bash